### ISSUE TITLE
how to get parameters at url and post form 

### ISSUE THREAD

**Issue by mlzboy** [starnight/MicroHttpServer#1]
hi,bro,thanks for u project,it's clean,simple.
if i want to use MicroHttpServer as a RESTful server
how to get parameters on URL like localhost:8001/?a=1&b=2 or in an post form webpage get post field value so I can handle on backend,thanks

**Comment by starnight** [comment]
Good question!
The feature you asked should be implemented in the CGI defined by [RFC 3875](https://tools.ietf.org/html/rfc3875), not HTTP defined by [RFC 2616](https://tools.ietf.org/html/rfc2616).  You can parse the data you want by your self, for example https://github.com/starnight/MicroHttpServer/blob/5be4d68993664ee54199c86bf6807b755cc719fe/c-version/app.c#L148  Or, use and link other CGI like programs.

**Comment by mlzboy** [comment]
thanks for u reply.
Since I use RESTful service,finally i use post json form data to slove this problem,frontend all use ajax to interact with backend.

also i have another question want to u give me some advice.
I want to use the MicroHttpServer on a openwrt or an nanopi with low memory and cpu hz environment.
And I want to embedded the backend logic(mostly CRUD to the sqlite) in to the  MicroHttpServer with language c,so I didn't need write two applications and config CGI settings.
And I have something confused me,it seems if i directly put my backend logic code in app.c it will take much time (query the database)and block other concurrency request ,how to solve this out,I'm still newbie on system programming,thanks

**Comment by starnight** [comment]
You can try I/O Multiplexing and non-blocking IO on socket.
