### ISSUE TITLE
/c-version/lib/server.c Bad Field Comparison

### ISSUE THREAD

**Issue by Stupid-Git** [starnight/MicroHttpServer#2]
Hi Starnight,  firstly, thanks for this simple server example.   
I had a problem when POSTing to /fib in that I kept getting 'Wrong' as the response, all the time, when using 'Postman' to talk with the server.
To fix this I changed
	`if(memcmp(req->Header.Fields[i].key, "Content-Length", 15) == 0) {`
to
        `if(memcmp(req->Header.Fields[i].key, "content-length", 15) == 0) { `
i.e. change the string to all lower-case.
I am sorry that I am ignorant as to the rules regarding the case of these header field parameters, but as the 'Postman' program is extensively used, so I am assuming that it is correct in it's operation.
So, I suspect the fields should be either lower-case or mixed-case, and so your code should be modified accordingly.

Cheers. Karel.

**Comment by starnight** [comment]
Maybe we need to re-read the RFC 2616 again to make sure what the specification said.
If it is not case sensitive, then we can have a fix for it.

**Comment by starnight** [comment]
Fixed!
