### ISSUE TITLE
Remote connection ?

### ISSUE THREAD

**Issue by Prabhu-Electro** [starnight/MicroHttpServer#3]
I see your conference in youtube.I saw the code from github.
In that when i am connect with internet to acess from remote.The ip 
address will change.Then how to know the ip of the remote 
server? how to connect it from remote(using internet)?
pls answer my question .I am engineering student to know how 
to do it?

**Comment by starnight** [comment]
I think you need OSI 7 layers' knowledge first.  Then, ICMP, NAT (Network Address Translation), DNS and DDNS (Dynamic DNS).  After that, you will have the answer.

**Comment by Prabhu-Electro** [comment]
Thankyou
